USE [AWARE]
GO

CREATE PROCEDURE [dbo].[usp_GetVistaGroupById]	
	@VistaGroupId UNIQUEIDENTIFIER
AS	
	SELECT ID, NAME, AWARE_GROUP_ID, FACILITY_ID FROM AWARE_VISTA_GROUP_MAPPINGS 
	WHERE ID = @VistaGroupId

GO


