USE [AWARE]
GO

/****** Object:  Table [dbo].[SQLTRX_LAST_UPDATE]    Script Date: 2/4/2015 10:07:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SQLTRX_LAST_UPDATE](
	[ID] [uniqueidentifier] NOT NULL,
	[FACILITY_ID] [uniqueidentifier] NULL,
	[LAST_UPDATE] [datetime] NULL,
 CONSTRAINT [PK_SQLTRX_LAST_UPDATE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SQLTRX_LAST_UPDATE] ADD  CONSTRAINT [DF_SQLTRX_LAST_UPDATE_ID]  DEFAULT (newid()) FOR [ID]
GO


